// <auto-generated />
namespace RunFast.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdjustGame_Card : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdjustGame_Card));
        
        string IMigrationMetadata.Id
        {
            get { return "201710212144490_AdjustGame_Card"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
